#!/bin/sh

[ "$1" = 'prereqs' ] && { exit 0; }

# Workaround: Removed netplan yaml file created in initramfs stage
# See also: https://askubuntu.com/questions/1228433/what-is-creating-run-netplan-eth0-yaml
reset_network_interfaces() {(
	for intf in /sys/class/net/*; do
		if [ "${intf##*/}" = "lo" ]; then
			continue
		fi
		if [ -f "/run/netplan/${intf##*/}.yaml" ]; then
			rm -f "/run/netplan/${intf##*/}.yaml"
		fi
		ip addr flush dev "${intf##*/}"
	done
)}

. /scripts/functions

reset_network_interfaces
