include_recipe File.expand_path('../../cookbooks/validate', __FILE__)
include_recipe File.expand_path('../../cookbooks/apt', __FILE__)
include_recipe File.expand_path('../../cookbooks/curl', __FILE__)
include_recipe File.expand_path('../../cookbooks/hostname', __FILE__)
include_recipe File.expand_path('../../cookbooks/linux-kernel', __FILE__)
include_recipe File.expand_path('../../cookbooks/minimal', __FILE__)
include_recipe File.expand_path('../../cookbooks/standard', __FILE__)
include_recipe File.expand_path('../../cookbooks/openssh', __FILE__)
include_recipe File.expand_path('../../cookbooks/overlayroot', __FILE__)
include_recipe File.expand_path('../../cookbooks/wireguard', __FILE__)
include_recipe File.expand_path('../../cookbooks/cloud-init', __FILE__)
# include_recipe File.expand_path('../../cookbooks/nvidia-cuda', __FILE__)
include_recipe File.expand_path('../../cookbooks/graphics-drivers', __FILE__)
include_recipe File.expand_path('../../cookbooks/desktop', __FILE__)
include_recipe File.expand_path('../../cookbooks/cleanup', __FILE__)
