include_recipe File.expand_path('../../cookbooks/validate', __FILE__)
include_recipe File.expand_path('../../cookbooks/apt', __FILE__)
include_recipe File.expand_path('../../cookbooks/hostname', __FILE__)
include_recipe File.expand_path('../../cookbooks/minimal', __FILE__)
include_recipe File.expand_path('../../cookbooks/standard', __FILE__)
include_recipe File.expand_path('../../cookbooks/openssh', __FILE__)
include_recipe File.expand_path('../../cookbooks/cloud-init', __FILE__)
