#!/bin/sh

[ "$1" = 'prereqs' ] && { exit 0; }

cloud_init_disable_resize_rootfs() {(
	for cmdline in $(cat /proc/cmdline); do
		case ${cmdline} in
			ds=*)
				datastore="${cmdline#ds=}"
				;;
			seednet=*)
				seednet="${cmdline#seednet=}"
				;;
		esac
	done

	if [ -z "${datastore}" ]; then
		return
	fi

	if [ "${datastore%%;*}" != "nocloud-net" ]; then
		return
	fi

	OLDIFS="$IFS"
	IFS=";"
	for cmdline in ${datastore}; do
		case ${cmdline} in
			s=*)
				seedfrom="${cmdline#s=}"
				;;
			seedfrom=*)
				seedfrom="${cmdline#seedfrom=}"
				;;
		esac
	done
	IFS="$OLDIFS"

	if [ -d "${rootmnt}/etc/cloud/cloud.cfg.d" ]; then
		if [ -z "${seedfrom}" ] && [ -n "${seednet}" ]; then
			echo 'resize_rootfs: false' > "${rootmnt}/etc/cloud/cloud.cfg.d/99_disable_resize_rootfs.cfg"
		fi
	fi
)}

. /scripts/functions

cloud_init_disable_resize_rootfs
