#!/bin/sh
# vim: set noet :

[ "$1" = 'prereqs' ] && { exit 0; }

disable_resize_rootfs() {(
	if [ "${BOOT:-}" != "live" ]; then
		return
	fi

	if [ ! -d "${rootmnt}/etc/cloud/cloud.cfg.d" ]; then
		return
	fi

	echo 'resize_rootfs: false' > "${rootmnt}/etc/cloud/cloud.cfg.d/99_disable_resize_rootfs.cfg"
)}

. /scripts/functions

disable_resize_rootfs
