#!/bin/sh
# vim: set noet :

[ "$1" = 'prereqs' ] && { exit 0; }

optional_wireless_network_interfaces() {(
	mkdir -p "/run/systemd/network"

	{
		echo "[Match]"
		echo "Type=wlan"
		echo ""
		echo "[Link]"
		echo "RequiredForOnline=no"
	} > "/run/systemd/network/20-wireless.network"
)}

. /scripts/functions

optional_wireless_network_interfaces
