#!/bin/sh
# vim: set noet :

[ "$1" = 'prereqs' ] && { exit 0; }

optional_ethernet_network_interfaces() {(
	mkdir -p "/run/systemd/network"

	{
		echo "[Match]"
		echo "Type=ether"
		echo ""
		echo "[Link]"
		echo "RequiredForOnline=no"
		echo ""
		echo "[Network]"
		echo "DHCP=yes"
		echo "LinkLocalAddressing=yes"
		echo "IPv6LinkLocalAddressGenerationMode=stable-privacy"
		echo "LLMNR=no"
		echo "MulticastDNS=yes"
	} > "/run/systemd/network/99-ethernet.network"
)}

. /scripts/functions

optional_ethernet_network_interfaces
