#!/bin/sh

[ "$1" = 'prereqs' ] && { exit 0; }

# Workaround: Removed netplan yaml file created in initramfs stage
# See also: https://askubuntu.com/questions/1228433/what-is-creating-run-netplan-eth0-yaml
reset_network_interfaces() {(
	if ! test -r "${rootmnt}/etc/cloud/cloud.cfg.d/99_nocloud_network_config.cfg"; then
		return 0
	fi

	for intf in /sys/class/net/*; do
		if [ "${intf##*/}" = "lo" ]; then
			continue
		fi

		if [ -f "/run/netplan/${intf##*/}.yaml" ]; then
			rm -f "/run/netplan/${intf##*/}.yaml"
		fi

		if [ -f "/run/net-${intf##*/}.conf" ]; then
			rm -f "/run/net-${intf##*/}.conf"
		fi

		ip -4 addr flush dev "${intf##*/}"
		ip -6 addr flush dev "${intf##*/}"
		ip -4 route flush dev "${intf##*/}"
		ip -6 route flush dev "${intf##*/}"
	done
)}

. /scripts/functions

reset_network_interfaces
