# frozen_string_literal: true

#
# Validate Variables - Backend
#

node.validate! do
  {
    powerdns: {
      backend: {
        bind: optional({
          'config':                 string,
          'check-interval':         optional(numeric),
          'dnssec-db':              optional(string),
          'dnssec-db-journal-mode': optional(string),
          'hybrid':                 optional(boolean),
          'ignore-broken-records':  optional(boolean),
          'autoprimaries':          optional(array_of(string)),
          'autoprimary-config':     optional(string),
          'autoprimary-destdir':    optional(string),
        }),
        gmysql: optional({
          'host':                  optional(string),
          'port':                  optional(numeric),
          'socket':                optional(string),
          'dbname':                optional(string),
          'user':                  optional(string),
          'group':                 optional(string),
          'password':              optional(string),
          'dnssec':                optional(boolean),
          'innodb-read-committed': optional(boolean),
          'ssl':                   optional(boolean),
          'timeout':               optional(numeric),
          'thread-cleanup':        optional(boolean),
        }),
        godbc: optional({
          # TODO
        }),
        gpgsql: optional({
          # TODO
        }),
        gsqlite3: optional({
          # TODO
        }),
        geoip: optional({
          # TODO
        }),
        ldap: optional({
          # TODO
        }),
        lmdb: optional({
          # TODO
        }),
        lua2: optional({
          # TODO
        }),
        mydns: optional({
          # TODO
        }),
        pipe: optional({
          # TODO
        }),
        remote: optional({
          # TODO
        }),
        tinydns: optional({
          # TODO
        }),
      },
    },
  }
end

#
# Validate Variables - Authoritative
#

node.validate! do
  {
    powerdns: {
      config: {
        authoritative: {
          '8bit-dns': optional(boolean),
          'allow-axfr-ips': optional(array_of(string)),
          'allow-dnsupdate-from': optional(array_of(string)),
          'allow-notify-from': optional(array_of(string)),
          'allow-unsigned-autoprimary': optional(boolean),
          'allow-unsigned-notify': optional(boolean),
          'allow-unsigned-supermaster': optional(boolean),
          'also-notify': optional(array_of(string)),
          'any-to-tcp': optional(boolean),
          'api': optional(boolean),
          'api-key': optional(string),
          'autosecondary': optional(boolean),
          'axfr-fetch-timeout': optional(numeric),
          'axfr-lower-serial': optional(boolean),
          'cache-ttl': optional(numeric),
          'carbon-instance': optional(string),
          'carbon-interval': optional(numeric),
          'carbon-namespace': optional(string),
          'carbon-ourname': optional(string),
          'carbon-server': optional(array_of(string)),
          'chroot': optional(string),
          'secondary-check-signature-freshness': optional(boolean),
          'config-dir': optional(string),
          'config-name': optional(string),
          'consistent-backends': optional(boolean),
          'control-console': optional(boolean),
          'daemon': optional(boolean),
          'default-api-rectify': optional(boolean),
          'default-catalog-zone': optional(string),
          'default-ksk-algorithm': optional(match(/^(?:rsasha1|rsasha256|rsasha512|ecdsa256|ecdsa384|ed25519|ed448)$/)),
          'default-ksk-size': optional(numeric),
          'default-publish-cdnskey': optional(numeric),
          'default-publish-cds': optional(array_of(numeric)),
          'default-soa-content': optional(string),
          'default-soa-edit': optional(string),
          'default-soa-edit-signed': optional(string),
          'default-ttl': optional(numeric),
          'default-zsk-algorithm': optional(match(/^(?:rsasha1|rsasha256|rsasha512|ecdsa256|ecdsa384|ed25519|ed448)$/)),
          'default-zsk-size': optional(numeric),
          'direct-dnskey': optional(boolean),
          'disable-axfr': optional(boolean),
          'disable-axfr-rectify': optional(boolean),
          'disable-syslog': optional(boolean),
          'distributor-threads': optional(numeric),
          'dname-processing': optional(boolean),
          'dnssec-key-cache-ttl': optional(numeric),
          'dnsupdate': optional(boolean),
          'dnsupdate-require-tsig': optional(boolean),
          'domain-metadata-cache-ttl': optional(numeric),
          'edns-cookie-secret': optional(string),
          'edns-subnet-processing': optional(boolean),
          'enable-lua-records': optional(boolean),
          'entropy-source': optional(string),
          'expand-alias': optional(boolean),
          'forward-dnsupdate': optional(boolean),
          'forward-notify': optional(array_of(string)),
          'guardian': optional(boolean),
          'ignore-unknown-settings': optional(array_of(string)),
          'include-dir': optional(string),
          'launch': optional(array_of(string)),
          'load-modules': optional(array_of(string)),
          'local-address': optional(array_of(string)),
          'local-address-nonexist-fail': optional(boolean),
          'local-port': optional(numeric),
          'log-dns-details': optional(boolean),
          'log-dns-queries': optional(boolean),
          'log-timestamp': optional(boolean),
          'logging-facility': optional(string),
          'loglevel': optional(numeric),
          'loglevel-show': optional(boolean),
          'lua-axfr-script': optional(string),
          'lua-consistent-hashes-cleanup-interval': optional(numeric),
          'lua-consistent-hashes-expire-delay': optional(numeric),
          'lua-dnsupdate-policy-script': optional(string),
          'lua-health-checks-expire-delay': optional(numeric),
          'lua-health-checks-interval': optional(numeric),
          'lua-prequery-script': optional(string),
          'lua-records-exec-limit': optional(numeric),
          'lua-records-insert-whitespace': optional(boolean),
          'master': optional(boolean),
          'max-cache-entries': optional(numeric),
          'max-ent-entries': optional(numeric),
          'max-generate-steps': optional(numeric),
          'max-nsec3-iterations': optional(numeric),
          'max-packet-cache-entries': optional(numeric),
          'max-queue-length': optional(numeric),
          'max-signature-cache-entries': optional(numeric),
          'max-tcp-connection-duration': optional(numeric),
          'max-tcp-connections': optional(numeric),
          'max-tcp-connections-per-client': optional(numeric),
          'max-tcp-transactions-per-conn': optional(numeric),
          'negquery-cache-ttl': optional(numeric),
          'no-shuffle': optional(boolean),
          'non-local-bind': optional(boolean),
          'only-notify': optional(array_of(string)),
          'outgoing-axfr-expand-alias': optional(boolean),
          'overload-queue-length': optional(numeric),
          'prevent-self-notification': optional(boolean),
          'primary': optional(boolean),
          'proxy-protocol-from': optional(array_of(string)),
          'proxy-protocol-maximum-size': optional(numeric),
          'query-cache-ttl': optional(numeric),
          'query-local-address': optional(array_of(string)),
          'query-logging': optional(boolean),
          'queue-limit': optional(numeric),
          'receiver-threads': optional(numeric),
          'resolver': optional(boolean),
          'retrieval-threads': optional(numeric),
          'reuseport': optional(boolean),
          'rng': optional(match(/^(?:auto|sodium|openssl|getrandom|arc4random|urandom|kiss)$/)),
          'secondary': optional(boolean),
          'secondary-do-renotify': optional(boolean),
          'security-poll-suffix': optional(string),
          'send-signed-notify': optional(boolean),
          'server-id': optional(string),
          'setgid': optional(string),
          'setuid': optional(string),
          'signing-threads': optional(numeric),
          'slave': optional(boolean),
          'slave-cycle-interval': optional(numeric),
          'slave-renotify': optional(boolean),
          'socket-dir': optional(string),
          'superslave': optional(boolean),
          'svc-autohints': optional(boolean),
          'tcp-control-address': optional(string),
          'tcp-control-port': optional(numeric),
          'tcp-control-range': optional(array_of(string)),
          'tcp-control-secret': optional(string),
          'tcp-fast-open': optional(numeric),
          'tcp-idle-timeout': optional(numeric),
          'traceback-handler': optional(boolean),
          'trusted-notification-proxy': optional(array_of(string)),
          'udp-truncation-threshold': optional(numeric),
          'upgrade-unknown-types': optional(boolean),
          'version-string': optional(match(/^(?:anonymous|powerdns|full)$/)),
          'webserver': optional(boolean),
          'webserver-address': optional(string),
          'webserver-allow-from': optional(array_of(string)),
          'webserver-hash-plaintext-credentials': optional(boolean),
          'webserver-loglevel': optional(match(/^(?:none|normal|detailed)$/)),
          'webserver-max-bodysize': optional(numeric),
          'webserver-connection-timeout': optional(numeric),
          'webserver-password': optional(string),
          'webserver-port': optional(numeric),
          'webserver-print-arguments': optional(boolean),
          'write-pid': optional(boolean),
          'xfr-cycle-interval': optional(numeric),
          'xfr-max-received-mbytes': optional(numeric),
          'zone-cache-refresh-interval': optional(numeric),
          'zone-metadata-cache-ttl': optional(numeric),
        },
      },
    },
  }
end

#
# Validate Variables - Recursor
#

node.validate! do
  {
    powerdns: {
      config: {
        recursor: {
          carbon: optional({
            instance: optional(string),
            interval: optional(integer),
            ns: optional(string),
            ourname: optional(string),
            server: optional(array_of(string)),
          }),
          dnssec: optional({
            aggressive_cache_max_nsec3_hash_cost: optional(integer),
            aggressive_cache_min_nsec3_hit_ratio: optional(integer),
            aggressive_nsec_cache_size: optional(integer),
            disabled_algorithms: optional(array_of(string)),
            log_bogus: optional(boolean),
            max_dnskeys: optional(integer),
            max_ds_per_zone: optional(integer),
            max_nsec3_hash_computations_per_query: optional(integer),
            max_nsec3s_per_record: optional(integer),
            max_rrsigs_per_record: optional(integer),
            max_signature_validations_per_query: optional(integer),
            negative_trustanchors: optional(array_of(string)),
            nsec3_max_iterations: optional(integer),
            signature_inception_skew: optional(integer),
            trustanchorfile: optional(string),
            trustanchorfile_interval: optional(integer),
            trustanchors: optional(array_of(string)),
            validation: optional(match(/^(?:off|process-no-validate|process|log-fail|validate)$/)),
            x_dnssec_names: optional(array_of(string)),
          }),
          ecs: optional({
            add_for: optional(array_of(string)),
            cache_limit_ttl: optional(integer),
            ipv4_bits: optional(integer),
            ipv4_cache_bits: optional(integer),
            ipv4_never_cache: optional(boolean),
            ipv6_bits: optional(integer),
            ipv6_cache_bits: optional(integer),
            ipv6_never_cache: optional(boolean),
            minimum_ttl_override: optional(integer),
            scope_zero_address: optional(string),
          }),
          incoming: optional({
            allow_from: optional(array_of(string)),
            allow_from_file: optional(string),
            allow_no_rd: optional(boolean),
            allow_notify_for: optional(array_of(string)),
            allow_notify_for_file: optional(string),
            allow_notify_from: optional(array_of(string)),
            allow_notify_from_file: optional(string),
            distribution_load_factor: optional(integer),
            distribution_pipe_buffer_size: optional(integer),
            distributor_threads: optional(integer),
            edns_padding_from: optional(array_of(string)),
            edns_padding_mode: optional(string),
            edns_padding_tag: optional(integer),
            gettag_needs_edns_options: optional(boolean),
            listen: optional(array_of(string)),
            max_concurrent_requests_per_tcp_connection: optional(integer),
            max_tcp_clients: optional(integer),
            max_tcp_per_client: optional(integer),
            max_tcp_queries_per_connection: optional(integer),
            max_udp_queries_per_round: optional(integer),
            non_local_bind: optional(boolean),
            pdns_distributes_queries: optional(boolean),
            port: optional(integer),
            proxy_protocol_exceptions: optional(array_of(string)),
            proxy_protocol_from: optional(array_of(string)),
            proxy_protocol_maximum_size: optional(integer),
            proxymappings: optional(array_of(string)),
            reuseport: optional(boolean),
            tcp_fast_open: optional(integer),
            tcp_timeout: optional(integer),
            udp_truncation_threshold: optional(integer),
            use_incoming_edns_subnet: optional(boolean),
          }),
          logging: optional({
            common_errors: optional(boolean),
            disable_syslog: optional(boolean),
            dnstap_framestream_servers: optional(array_of(string)),
            dnstap_nod_framestream_servers: optional(array_of(string)),
            facility: optional(string),
            loglevel: optional(integer),
            outgoing_protobuf_servers: optional(array_of(string)),
            protobuf_mask_v4: optional(integer),
            protobuf_mask_v6: optional(integer),
            protobuf_servers: optional(array_of(string)),
            protobuf_use_kernel_timestamp: optional(boolean),
            quiet: optional(boolean),
            rpz_changes: optional(boolean),
            statistics_interval: optional(integer),
            structured_logging: optional(boolean),
            structured_logging_backend: optional(string),
            timestamp: optional(boolean),
            trace: optional(string),
          }),
          nod: optional({
            db_size: optional(integer),
            db_snapshot_interval: optional(integer),
            history_dir: optional(string),
            ignore_list: optional(array_of(string)),
            ignore_list_file: optional(string),
            log: optional(boolean),
            lookup: optional(string),
            pb_tag: optional(string),
            tracking: optional(boolean),
            unique_response_db_size: optional(integer),
            unique_response_history_dir: optional(string),
            unique_response_ignore_list: optional(array_of(string)),
            unique_response_ignore_list_file: optional(string),
            unique_response_log: optional(boolean),
            unique_response_pb_tag: optional(string),
            unique_response_tracking: optional(boolean),
          }),
          outgoing: optional({
            bypass_server_throttling_probability: optional(integer),
            dont_query: optional(array_of(string)),
            dont_throttle_names: optional(array_of(string)),
            dont_throttle_netmasks: optional(array_of(string)),
            dot_to_auth_names: optional(array_of(string)),
            dot_to_port_853: optional(boolean),
            edns_bufsize: optional(integer),
            edns_padding: optional(boolean),
            edns_subnet_allow_list: optional(array_of(string)),
            lowercase: optional(boolean),
            max_busy_dot_probes: optional(integer),
            max_ns_address_qperq: optional(integer),
            max_ns_per_resolve: optional(integer),
            max_qperq: optional(integer),
            network_timeout: optional(integer),
            non_resolving_ns_max_fails: optional(integer),
            non_resolving_ns_throttle_time: optional(integer),
            server_down_max_fails: optional(integer),
            server_down_throttle_time: optional(integer),
            single_socket: optional(boolean),
            source_address: optional(array_of(string)),
            tcp_fast_open_connect: optional(boolean),
            tcp_max_idle_ms: optional(integer),
            tcp_max_idle_per_auth: optional(integer),
            tcp_max_idle_per_thread: optional(integer),
            tcp_max_queries: optional(integer),
            udp_source_port_avoid: optional(array_of(string)),
            udp_source_port_max: optional(integer),
            udp_source_port_min: optional(integer),
          }),
          packetcache: optional({
            disable: optional(boolean),
            max_entries: optional(integer),
            negative_ttl: optional(integer),
            servfail_ttl: optional(integer),
            shards: optional(integer),
            ttl: optional(integer),
          }),
          recordcache: optional({
            limit_qtype_any: optional(boolean),
            locked_ttl_perc: optional(integer),
            max_cache_bogus_ttl: optional(integer),
            max_entries: optional(integer),
            max_negative_ttl: optional(integer),
            max_rrset_size: optional(integer),
            max_ttl: optional(integer),
            refresh_on_ttl_perc: optional(integer),
            serve_stale_extensions: optional(integer),
            shards: optional(integer),
            zonetocaches: optional(integer),
          }),
          recursor: optional({
            allow_trust_anchor_query: optional(boolean),
            allowed_additional_qtypes: optional(array_of(string)),
            any_to_tcp: optional(boolean),
            auth_zones: optional(array_of(string)),
            chroot: optional(string),
            config_dir: optional(string),
            config_name: optional(string),
            cpu_map: optional(string),
            daemon: optional(boolean),
            dns64_prefix: optional(string),
            etc_hosts_file: optional(string),
            event_trace_enabled: optional(integer),
            export_etc_hosts: optional(boolean),
            export_etc_hosts_search_suffix: optional(string),
            extended_resolution_errors: optional(boolean),
            forward_zones: optional(array_of({zone: string, forwarders: array_of(string)})),
            forward_zones_file: optional(string),
            forward_zones_recurse: optional(array_of({zone: string, forwarders: array_of(string)})),
            hint_file: optional(string),
            ignore_unknown_settings: optional(array_of(string)),
            include_dir: optional(string),
            latency_statistic_size: optional(integer),
            lua_config_file: optional(string),
            lua_dns_script: optional(string),
            lua_global_include_dir: optional(string),
            lua_maintenance_interval: optional(integer),
            lua_start_stop_script: optional(string),
            max_chain_length: optional(integer),
            max_cnames_followed: optional(integer),
            max_generate_steps: optional(integer),
            max_include_depth: optional(integer),
            max_mthreads: optional(integer),
            max_recursion_depth: optional(integer),
            max_total_msec: optional(integer),
            minimum_ttl_override: optional(integer),
            nothing_below_nxdomain: optional(string),
            public_suffix_list_file: optional(string),
            qname_max_minimize_count: optional(integer),
            qname_minimization: optional(boolean),
            qname_minimize_one_label: optional(integer),
            root_nx_trust: optional(boolean),
            rpzs: optional(array_of(string)),
            save_parent_ns_set: optional(boolean),
            security_poll_suffix: optional(string),
            serve_rfc1918: optional(boolean),
            serve_rfc6303: optional(boolean),
            server_id: optional(string),
            setgid: optional(string),
            setuid: optional(string),
            socket_dir: optional(string),
            socket_group: optional(string),
            socket_mode: optional(string),
            socket_owner: optional(string),
            sortlists: optional(array_of(string)),
            spoof_nearmiss_max: optional(integer),
            stack_cache_size: optional(integer),
            stack_size: optional(integer),
            stats_api_disabled_list: optional(array_of(string)),
            stats_carbon_disabled_list: optional(array_of(string)),
            stats_rec_control_disabled_list: optional(array_of(string)),
            stats_ringbuffer_entries: optional(integer),
            stats_snmp_disabled_list: optional(array_of(string)),
            system_resolver_interval: optional(integer),
            system_resolver_self_resolve_check: optional(boolean),
            system_resolver_ttl: optional(integer),
            tcp_threads: optional(integer),
            threads: optional(integer),
            version_string: optional(string),
            write_pid: optional(boolean),
          }),
          snmp: optional({
            agent: optional(boolean),
            daemon_socket: optional(string),
          }),
          webservice: optional({
            address: optional(string),
            allow_from: optional(array_of(string)),
            api_dir: optional(string),
            api_key: optional(string),
            hash_plaintext_credentials: optional(boolean),
            loglevel: optional(string),
            password: optional(string),
            port: optional(integer),
            webserver: optional(boolean),
          }),
        },
      },
    },
  }
end
