# frozen_string_literal: true

#
# Check Distribution
#

unless node[:target][:distribution].match(/^ubuntu$/)
  return
end

#
# Check Architecture
#

unless node[:target][:architecture].match(/^(?:amd64|i386|armhf|arm64)$/)
  return
end

#
# Check Role
#

unless node[:target][:role].match(/desktop/)
  return
end

#
# Japanese Packages
#

package 'language-pack-ja'
package 'language-pack-gnome-ja'
package 'gnome-user-docs-ja'
package 'fonts-noto-cjk-extra'

#
# Input Method
#

package 'fcitx5'
package 'fcitx5-mozc'

#
# Default Input Method for Fcitx5
#

# im-config logs through systemd-cat whenever it is installed, which fails in
# the chroot without journald, so write the same signed file it would write.
# The signature is the output of:
#   printf '# im-config(8) generated by mitamae\nrun_im fcitx5\n' | md5sum
%w[/etc/X11/xinit/xinputrc /etc/skel/.xinputrc].each do |path|
  file path do
    owner 'root'
    group 'root'
    mode  '0644'
    content [
      '# im-config(8) generated by mitamae',
      'run_im fcitx5',
      '# im-config signature: ef23d27dc75e3ad5d4ed71eb0e58731f  -',
      '',
    ].join("\n")
  end
end

# im-config 0.59 dropped Wayland support, so on the Wayland-only GNOME of
# resolute it neither exports the IM variables nor launches fcitx5, and the
# Ubuntu fcitx5 package ships no autostart entry of its own.
if node[:target][:suite].match?(/^resolute$/)
  file '/etc/environment.d/90-fcitx5.conf' do
    owner 'root'
    group 'root'
    mode  '0644'
    content [
      'XMODIFIERS=@im=fcitx',
      'GTK_IM_MODULE=fcitx',
      'QT_IM_MODULE=fcitx',
      'SDL_IM_MODULE=fcitx',
      '',
    ].join("\n")
  end

  file '/etc/xdg/autostart/org.fcitx.Fcitx5.desktop' do
    owner 'root'
    group 'root'
    mode  '0644'
    content [
      '[Desktop Entry]',
      'Name=Fcitx 5',
      'Exec=/usr/bin/fcitx5',
      'Icon=fcitx',
      'Terminal=false',
      'Type=Application',
      'NoDisplay=true',
      'X-GNOME-AutoRestart=false',
      'X-GNOME-Autostart-Notify=false',
      '',
    ].join("\n")
  end
end

file '/usr/share/glib-2.0/schemas/99_input-method.gschema.override' do
  owner 'root'
  group 'root'
  mode  '0644'
  content [
    '[org.gnome.settings-daemon.plugins.keyboard]',
    'active=false',
  ].join("\n")
  notifies :run, 'execute[glib-compile-schemas /usr/share/glib-2.0/schemas]'
end

#
# Compile Glib Schemas
#

execute 'glib-compile-schemas /usr/share/glib-2.0/schemas' do
  action :nothing
end

#
# Home Directory Locale
#

file '/etc/xdg/autostart/xdg-user-dirs.desktop' do
  action :edit
  block do |content|
    content.gsub!(/^Exec=xdg-user-dirs-update$/, 'Exec=env LC_ALL=C xdg-user-dirs-update')
  end
end

file '/etc/xdg/autostart/user-dirs-update-gtk.desktop' do
  action :edit
  block do |content|
    content.gsub!(/^Exec=xdg-user-dirs-gtk-update$/, 'Exec=env LC_ALL=C xdg-user-dirs-gtk-update')
  end
end
