# frozen_string_literal: true

#
# Check Distribution
#

unless node[:target][:distribution].match(/^debian$/)
  return
end

#
# Check Architecture
#

unless node[:target][:architecture].match(/^(?:amd64|i386|armhf|arm64)$/)
  return
end

#
# Check Role
#

unless node[:target][:role].match(/desktop/)
  return
end

#
# Japanese Packages
#

package 'task-japanese'
package 'task-japanese-desktop'

#
# Input Method
#

package 'fcitx5'
package 'fcitx5-mozc'

#
# Default Input Method for Fcitx5
#

# im-config logs through systemd-cat whenever it is installed, which fails in
# the chroot without journald, so write the same signed file it would write.
# The signature is the output of:
#   printf '# im-config(8) generated by mitamae\nrun_im fcitx5\n' | md5sum
%w[/etc/X11/xinit/xinputrc /etc/skel/.xinputrc].each do |path|
  file path do
    owner 'root'
    group 'root'
    mode  '0644'
    content [
      '# im-config(8) generated by mitamae',
      'run_im fcitx5',
      '# im-config signature: ef23d27dc75e3ad5d4ed71eb0e58731f  -',
      '',
    ].join("\n")
  end
end

#
# Home Directory Locale
#

file '/etc/xdg/autostart/xdg-user-dirs.desktop' do
  action :edit
  block do |content|
    content.gsub!(/^Exec=xdg-user-dirs-update$/, 'Exec=env LC_ALL=C xdg-user-dirs-update')
  end
end

file '/etc/xdg/autostart/user-dirs-update-gtk.desktop' do
  action :edit
  block do |content|
    content.gsub!(/^Exec=xdg-user-dirs-gtk-update$/, 'Exec=env LC_ALL=C xdg-user-dirs-gtk-update')
  end
end

# Newer xdg-user-dirs and xdg-user-dirs-gtk mark their autostart entries with
# X-systemd-skip=true and run these user units instead, so the edits above no
# longer take effect on systemd managed sessions.
%w[xdg-user-dirs user-dirs-update-gtk].each do |unit|
  directory "/etc/systemd/user/#{unit}.service.d" do
    owner 'root'
    group 'root'
    mode  '0755'
  end

  file "/etc/systemd/user/#{unit}.service.d/locale.conf" do
    owner 'root'
    group 'root'
    mode  '0644'
    content [
      '[Service]',
      'Environment=LC_ALL=C',
    ].join("\n").concat("\n")
  end
end
