name: CI
on:
  push:
    branches:
    - master
  schedule:
  - cron: '35 17 * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
        - info
        - debug
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  matrix:
    name: Setup matrix
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.matrix.outputs.targets }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: NVIDIA vGPU Repository
      env:
        APT_REPO_PPA_NVIDIA_VGPU_KEYRING_UID: ${{ secrets.APT_REPO_PPA_NVIDIA_VGPU_KEYRING_UID }}
        APT_REPO_PPA_NVIDIA_VGPU_KEYRING_FINGER_PRINT: ${{ secrets.APT_REPO_PPA_NVIDIA_VGPU_KEYRING_FINGER_PRINT }}
        APT_REPO_PPA_NVIDIA_VGPU_KEYRING_URL: ${{ secrets.APT_REPO_PPA_NVIDIA_VGPU_KEYRING_URL }}
        APT_REPO_PPA_NVIDIA_VGPU_URL: ${{ secrets.APT_REPO_PPA_NVIDIA_VGPU_URL }}
      run: |
        echo "APT_REPO_PPA_NVIDIA_VGPU_KEYRING_UID=${APT_REPO_PPA_NVIDIA_VGPU_KEYRING_UID}" >> $GITHUB_ENV
        echo "APT_REPO_PPA_NVIDIA_VGPU_KEYRING_FINGER_PRINT=${APT_REPO_PPA_NVIDIA_VGPU_KEYRING_FINGER_PRINT}" >> $GITHUB_ENV
        echo "APT_REPO_PPA_NVIDIA_VGPU_KEYRING_URL=${APT_REPO_PPA_NVIDIA_VGPU_KEYRING_URL}" >> $GITHUB_ENV
        echo "APT_REPO_PPA_NVIDIA_VGPU_URL=${APT_REPO_PPA_NVIDIA_VGPU_URL}" >> $GITHUB_ENV
    - name: Setup matrix
      id: matrix
      run: echo "targets=$(rake github:actions:all)" >> $GITHUB_OUTPUT
  build-and-publish:
    needs: matrix
    name: ${{ matrix.target.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: ${{ fromJson(needs.matrix.outputs.targets) }}
    env:
      TARGET_NAME: ${{ matrix.target.name }}
      RELEASE_DIR: ${{ matrix.target.dir }}
      INITRAMFS_COMPRESS: xz
      ROOTFS_ARCHIVE_FORMAT_TARBALL: xz
      ROOTFS_ARCHIVE_FORMAT_SQUASHFS: xz
    steps:
    #
    # Environment Variables
    #
    - name: Log Level
      if: github.event.inputs.logLevel != ''
      env:
        MITAMAE_LOG_LEVEL: ${{ github.event.inputs.logLevel }}
      run: |
        echo "LOG_LEVEL=${MITAMAE_LOG_LEVEL}" >> $GITHUB_ENV
    - name: NVIDIA vGPU Repository
      env:
        APT_REPO_PPA_NVIDIA_VGPU_KEYRING_UID: ${{ secrets.APT_REPO_PPA_NVIDIA_VGPU_KEYRING_UID }}
        APT_REPO_PPA_NVIDIA_VGPU_KEYRING_FINGER_PRINT: ${{ secrets.APT_REPO_PPA_NVIDIA_VGPU_KEYRING_FINGER_PRINT }}
        APT_REPO_PPA_NVIDIA_VGPU_KEYRING_URL: ${{ secrets.APT_REPO_PPA_NVIDIA_VGPU_KEYRING_URL }}
        APT_REPO_PPA_NVIDIA_VGPU_URL: ${{ secrets.APT_REPO_PPA_NVIDIA_VGPU_URL }}
      run: |
        echo "APT_REPO_PPA_NVIDIA_VGPU_KEYRING_UID=${APT_REPO_PPA_NVIDIA_VGPU_KEYRING_UID}" >> $GITHUB_ENV
        echo "APT_REPO_PPA_NVIDIA_VGPU_KEYRING_FINGER_PRINT=${APT_REPO_PPA_NVIDIA_VGPU_KEYRING_FINGER_PRINT}" >> $GITHUB_ENV
        echo "APT_REPO_PPA_NVIDIA_VGPU_KEYRING_URL=${APT_REPO_PPA_NVIDIA_VGPU_KEYRING_URL}" >> $GITHUB_ENV
        echo "APT_REPO_PPA_NVIDIA_VGPU_URL=${APT_REPO_PPA_NVIDIA_VGPU_URL}" >> $GITHUB_ENV
    #
    # Prepare
    #
    - name: Update
      run: sudo apt-get -y update
    #
    # Build Image
    #
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 1
    - name: Initialize
      id: initialize
      run: rake ${TARGET_NAME}:initialize
    - name: Provision
      id: provision
      run: rake ${TARGET_NAME}:provision
    - name: Finalize
      id: finalize
      run: rake ${TARGET_NAME}:finalize
    #
    # Build Artifacts
    #
    - name: Sizes
      if: success()
      run: ls -lah releases/${RELEASE_DIR}/
    - name: Packages
      if: success()
      run: cat releases/${RELEASE_DIR}/packages.manifest
    - name: Checksums
      if: success()
      run: cat releases/${RELEASE_DIR}/SHA256SUMS
    #
    # Check Mount Point
    #
    - name: Check Mount Point
      if: failure()
      run: findmnt -aR /
    - name: Check Open Process
      if: failure()
      run: lsof /
    #
    # Check Publish Target
    #
    - name: Check Publish Target
      run: rake github:actions:publish:${TARGET_NAME} >> $GITHUB_ENV
    #
    # Check Difference
    #
    - name: Download Packages Manifest
      if: env.PUBLISH == 'true'
      env:
        S3_BUCKET_URL: ${{ secrets.S3_BUCKET_URL }}
      run: |
        wget -qO /tmp/packages.manifest ${S3_BUCKET_URL}/${RELEASE_DIR}/packages.manifest || touch /tmp/packages.manifest
    - name: Check Difference
      if: env.PUBLISH == 'true'
      run: diff -u /tmp/packages.manifest releases/${RELEASE_DIR}/packages.manifest && echo 'PUBLISH_SYNC=true' >> $GITHUB_ENV || exit 0
    #
    # Setup Rclone
    #
    - name: Setup rclone
      if: env.PUBLISH_SYNC == 'true'
      run: curl https://rclone.org/install.sh | sudo bash
    #
    # Publish S3
    #
    - name: Publish
      if: env.PUBLISH_SYNC == 'true'
      env:
        RCLONE_S3_PROVIDER: ${{ secrets.S3_PROVIDER }}
        RCLONE_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT_URL }}
        RCLONE_S3_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        RCLONE_S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: >-
        rclone sync -v
        --config /dev/null
        --retries 360
        --retries-sleep 10s
        --low-level-retries 30
        --stats 1s
        --stats-file-name-length 0
        --stats-one-line
        releases/${RELEASE_DIR}
        :s3:mitamae-cloud-image/${RELEASE_DIR}
