name: Ubuntu Cloud Image
on: [push, pull_request]
jobs:
  ubuntu-bionic-generic-amd64-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        fetch-depth: 1
    - name: Update
      run: sudo apt-get -y update
    - name: Initialize
      run: make initialize
      env:
        PROFILE_YAML: profiles/ubuntu/bionic/generic/amd64/server.yml
        APT_REPO_URL_UBUNTU: http://azure.archive.ubuntu.com/ubuntu/
    - name: Build image
      run: make build
      env:
        PROFILE_YAML: profiles/ubuntu/bionic/generic/amd64/server.yml
        APT_REPO_URL_UBUNTU: http://azure.archive.ubuntu.com/ubuntu/
    - name: Finalize
      run: make finalize
      env:
        PROFILE_YAML: profiles/ubuntu/bionic/generic/amd64/server.yml
        APT_REPO_URL_UBUNTU: http://azure.archive.ubuntu.com/ubuntu/
