name: Ubuntu
on: [push, pull_request]
env:
  APT_REPO_URL_UBUNTU: http://azure.archive.ubuntu.com/ubuntu
  APT_REPO_URL_UBUNTU_PORTS: http://azure.ports.ubuntu.com
jobs:
  ubuntu-bionic-generic-server-amd64:
    name: Bionic Generic Server (amd64)
    runs-on: ubuntu-latest
    env:
      PROFILE_YAML: profiles/ubuntu/bionic/generic/amd64/server.yml
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        fetch-depth: 1
    - name: Update
      run: sudo apt-get -y update
    - name: Initialize
      run: rake ubuntu_bionic_generic_amd64_server:initialize
    - name: Provision
      run: rake ubuntu_bionic_generic_amd64_server:provision
    - name: Finalize
      run: rake ubuntu_bionic_generic_amd64_server:finalize
  ubuntu-bionic-generic-server-arm64:
    name: Bionic Generic Server (arm64)
    runs-on: ubuntu-latest
    env:
      PROFILE_YAML: profiles/ubuntu/bionic/generic/arm64/server.yml
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        fetch-depth: 1
    - name: Update
      run: sudo apt-get -y update
    - name: Initialize
      run: rake ubuntu_bionic_generic_arm64_server:initialize
    - name: Provision
      run: rake ubuntu_bionic_generic_arm64_server:provision
    - name: Finalize
      run: rake ubuntu_bionic_generic_arm64_server:finalize
