name: Build
on: [push]
env:
  APT_REPO_URL_UBUNTU: http://azure.archive.ubuntu.com/ubuntu
  APT_REPO_URL_UBUNTU_PORTS: http://azure.ports.ubuntu.com/ubuntu-ports
jobs:
  build:
    name: ${{ matrix.distro }} ${{ matrix.release }} ${{ matrix.kernel }} ${{ matrix.profile }} (${{ matrix.arch }})
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        distro:  [ubuntu]
        release: [focal]
        kernel:  [generic-hwe]
        profile: [server]
        arch:    [amd64]
        # distro:  [ubuntu, debian]
        # include:
        # - distro: ubuntu
        #   release: [bionic, focal]
        #   kernel:  [generic, generic-hwe]
        #   profile: [server, server-nvidia, desktop, desktop-nvidia]
        #   arch:    [amd64, arm64]
        # - distro: debian
        #   release: [buster]
        #   kernel:  [generic]
        #   profile: [server, desktop]
        #   arch:    [amd64, arm64]
    env:
      PROFILE_YAML: profiles/${{ matrix.distro }}/${{ matrix.release }}/${{ matrix.kernel }}/${{ matrix.arch }}/${{ matrix.profile }}.yml
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        fetch-depth: 1
    - name: Update
      run: sudo apt-get -y update
    - name: Initialize
      run: rake ${{ matrix.distro }}_${{ matrix.release }}_${{ matrix.kernel }}_${{ matrix.arch }}_${{ matrix.profile }}:initialize
    - name: Provision
      run: rake ${{ matrix.distro }}_${{ matrix.release }}_${{ matrix.kernel }}_${{ matrix.arch }}_${{ matrix.profile }}:provision
    - name: Finalize
      run: rake ${{ matrix.distro }}_${{ matrix.release }}_${{ matrix.kernel }}_${{ matrix.arch }}_${{ matrix.profile }}:finalize
    - name: Packages
      run: cat releases/${{ matrix.distro }}/${{ matrix.release }}/${{ matrix.kernel }}/${{ matrix.arch }}/${{ matrix.profile }}/packages.manifest
