name: Ubuntu
on: [push, pull_request]
env:
  APT_REPO_URL_UBUNTU: http://azure.archive.ubuntu.com/ubuntu
  APT_REPO_URL_UBUNTU_PORTS: http://azure.ports.ubuntu.com/ubuntu-ports
  DISABLE_SQUASHFS: true
  DISABLE_TARBALL: true
jobs:
  ubuntu-bionic-generic-server-amd64:
    name: Bionic Generic Server (amd64)
    runs-on: ubuntu-latest
    env:
      PROFILE_YAML: profiles/ubuntu/bionic/generic-server-amd64.yml
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        fetch-depth: 1
    - name: Update
      run: sudo apt-get -y update
    - name: Initialize
      run: rake ubuntu_bionic_generic-server-amd64:initialize
    - name: Provision
      run: rake ubuntu_bionic_generic-server-amd64:provision
    - name: Finalize
      run: rake ubuntu_bionic_generic-server-amd64:finalize
    - name: Packages
      run: cat releases/ubuntu/bionic/generic/server/amd64/packages.manifest
  ubuntu-bionic-generic-server-arm64:
    name: Bionic Generic Server (arm64)
    runs-on: ubuntu-latest
    env:
      PROFILE_YAML: profiles/ubuntu/bionic/generic-server-arm64.yml
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        submodules: true
        fetch-depth: 1
    - name: Update
      run: sudo apt-get -y update
    - name: Initialize
      run: rake ubuntu_bionic_generic-server-arm64:initialize
    - name: Provision
      run: rake ubuntu_bionic_generic-server-arm64:provision
    - name: Finalize
      run: rake ubuntu_bionic_generic-server-arm64:finalize
    - name: Packages
      run: cat releases/ubuntu/bionic/generic/server/arm64/packages.manifest
