name: Ubuntu Cloud Image
on: [push, pull_request]
jobs:
  ubuntu-bionic-generic-amd64-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Required
      run: |-
        sudo apt-get -yqq update
        sudo apt-get -yqq install debootstrap
        make mitamae
        cat /etc/apt/sources.list
