name: Ubuntu Cloud Image
on: [push, pull_request]
jobs:
  ubuntu-bionic-generic-amd64-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Required
      run: |-
        sudo apt-get -y update
        sudo apt-get -y --no-install-recommends install cdebootstrap ubuntu-keyring systemd-container
        make mitamae
    - name: Debootstrap
      run: make ubuntu-bionic-generic-amd64-server
      env:
        APT_REPO_URL_UBUNTU: http://azure.archive.ubuntu.com/ubuntu/
